package com.example.salarycalculator.domain

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object TaxPackZipExporter {

    /**
     * Bundles all annual payroll documents (P60, SA100, CSV ledger, ICS shift calendar, and Annual Shift PDF) into a single ZIP archive.
     */
    fun createTaxPackZip(
        context: Context,
        historyRecords: List<MonthlySalaryRecord>,
        annualShifts: Map<Int, Map<Int, Double>> = emptyMap(),
        taxYearLabel: String = "2024/2025",
        year: Int = 2025,
        hourlyRate: Double = 15.0
    ): File {
        val sanitizedYear = taxYearLabel.replace("/", "_").replace(" ", "_")
        val zipFile = File(context.cacheDir, "Salary_Tax_Pack_${sanitizedYear}.zip")
        val zos = ZipOutputStream(FileOutputStream(zipFile))

        val totalGross = historyRecords.sumOf { it.grossPay }
        val totalTax = historyRecords.sumOf { it.incomeTax }
        val totalNI = historyRecords.sumOf { it.nationalInsurance }
        val totalNet = historyRecords.sumOf { it.netPay }

        // 1. P60 PDF
        try {
            if (historyRecords.isNotEmpty()) {
                val p60File = P60Generator.generateP60Pdf(context = context, taxYearLabel = taxYearLabel, records = historyRecords)
                addFileToZip(zos, p60File, "1_Annual_P60_Certificate.pdf")
            }
        } catch (_: Exception) {}

        // 2. SA100 PDF
        try {
            if (historyRecords.isNotEmpty()) {
                val sa100Summary = Sa100Generator.generateFromRecords(historyRecords, taxYearLabel)
                val sa100File = Sa100Generator.generatePdf(context = context, summary = sa100Summary)
                addFileToZip(zos, sa100File, "2_HMRC_SA100_SelfAssessment.pdf")
            }
        } catch (_: Exception) {}

        // 3. Shift Calendar ICS
        try {
            if (annualShifts.isNotEmpty()) {
                val icsContent = IcsCalendarExporter.generateAnnualIcsContent(year, annualShifts)
                addStringToZip(zos, icsContent, "3_Full_Year_Shift_Calendar.ics")
            }
        } catch (_: Exception) {}

        // 4. Payroll Ledger CSV
        try {
            if (historyRecords.isNotEmpty()) {
                val csvFile = CsvSalaryExporter.exportHistoryCsv(context, historyRecords)
                addFileToZip(zos, csvFile, "4_Payroll_History_Ledger.csv")
            }
        } catch (_: Exception) {}

        // 5. Annual Shift Overview PDF
        try {
            if (annualShifts.isNotEmpty()) {
                val annualShiftPdf = AnnualShiftPdfGenerator.generateAnnualShiftPdf(
                    context = context,
                    year = year,
                    annualShifts = annualShifts,
                    hourlyRate = hourlyRate
                )
                addFileToZip(zos, annualShiftPdf, "5_Annual_Shift_Poster.pdf")
            }
        } catch (_: Exception) {}

        // 6. Readme Summary TXT
        val readmeContent = """
            =======================================================
            SALARY CALCULATOR — OFFICIAL ANNUAL TAX PACK
            Tax Year: $taxYearLabel
            Generated: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.UK).format(Date())}
            =======================================================

            ANNUAL SUMMARY:
            • Total Months Recorded: ${historyRecords.size}
            • Total Gross Income: £${"%,.2f".format(totalGross)}
            • Total PAYE Tax Deducted: £${"%,.2f".format(totalTax)}
            • Total Class 1 National Insurance: £${"%,.2f".format(totalNI)}
            • Total Net Take-Home: £${"%,.2f".format(totalNet)}

            INCLUDED DOCUMENTS:
            1. 1_Annual_P60_Certificate.pdf — Official A4 End-of-Year Certificate
            2. 2_HMRC_SA100_SelfAssessment.pdf — SA100/SA102 Box 1-7 Tax Return
            3. 3_Full_Year_Shift_Calendar.ics — RFC 5545 iCalendar importable to Google/Apple Calendar
            4. 4_Payroll_History_Ledger.csv — Raw spreadsheet ledger for Excel/Sheets
            5. 5_Annual_Shift_Poster.pdf — Printable 12-Month Year-at-a-Glance Shift Calendar

            Generated by Salary Calculator Android App.
            =======================================================
        """.trimIndent()
        addStringToZip(zos, readmeContent, "README_Tax_Pack.txt")

        zos.finish()
        zos.close()

        return zipFile
    }

    private fun addFileToZip(zos: ZipOutputStream, file: File, entryName: String) {
        if (!file.exists()) return
        val fis = FileInputStream(file)
        val entry = ZipEntry(entryName)
        zos.putNextEntry(entry)
        fis.copyTo(zos)
        zos.closeEntry()
        fis.close()
    }

    private fun addStringToZip(zos: ZipOutputStream, content: String, entryName: String) {
        val entry = ZipEntry(entryName)
        zos.putNextEntry(entry)
        zos.write(content.toByteArray(Charsets.UTF_8))
        zos.closeEntry()
    }

    /**
     * Shares the generated tax pack ZIP archive via Android Sharesheet.
     */
    fun shareZip(context: Context, zipFile: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            zipFile
        )
        val sendIntent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_STREAM, uri)
            type = "application/zip"
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(sendIntent, "Share ${zipFile.name}"))
    }
}
